[package]
name = "electro-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
cidr-utils = "0.6.1"
lazy_static = "1.5.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
ureq = "3.0.9"
